FROM zhangsikai/skyblog:skyflask

MAINTAINER sikaizhang

RUN mkdir /app

ENV WORK_PATH /app

WORKDIR $WORK_PATH

# Copy the requirements file in order to install
# Python dependencies
COPY requirements.txt .


# Install Python dependencies
RUN pip install -r requirements.txt

# We copy the rest of the codebase into the image
COPY . .

EXPOSE 5000

RUN echo Hello Sikai

RUN python -v

RUN gunicorn -v

ENTRYPOINT ["gunicorn", "-b 0.0.0.0:5000", "--access-logfile", "web.log", "web:app"]
