# Dockerfile-nginx
FROM nginx:latest

# Nginx will listen on this port
EXPOSE 8080

# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

RUN mkdir /etc/nginx/logs


COPY data/nginx/nginx.conf /etc/nginx/nginx.conf
