# user sikaizhang

# docker-compose.yml
version: '3'
services:
#  flask:
#    image: skyblogger
#    build:
#      context: .
#      dockerfile: Dockerfile-app
#    ports:
#      - 5000:5000
#  nginx:
#    image: skyblogger-nginx
#    build:
#      context: .
#      dockerfile: Dockerfile-nginx
#    ports:
#      - 80:8080
#    depends_on:
#      - flask
  mongo:
    image: mongo
    restart: always
    volumes:
      - "/data/db:/data/db"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
