# Dockerfile-nginx
FROM nginx:latest

# Nginx will listen on this port
EXPOSE 5000

# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

RUN mkdir /etc/nginx/logs

COPY nginx.conf /etc/nginx/nginx.conf
